from collections import OrderedDict
import os
import json

APP_NAME = "Azulyn"
APPDATA_DIR = os.path.join(os.environ["APPDATA"], APP_NAME)
CONFIG_PATH = os.path.join(APPDATA_DIR, "keybinds.json")

DESIRED_ORDER = [
    # GEAR SWAPS
    "Abyssal_Scourge",
    "Bow_of_the_Last_Guardian",
    "Champion's_Ring",
    "Channeller's_Ring",
    "Cinderbane_Gloves",
    "Cryptbloom_Boots",
    "Cryptbloom_Bottoms",
    "Cryptbloom_Gloves",
    "Cryptbloom_Helm",
    "Cryptbloom_Top",
    "Dark_Bow",
    "Dark_Bow_In_EOF",
    "Dark_Shard_Of_Leng",
    "Dark_Sliver_Of_Leng",
    "Death_Guard",
    "Death_Guard_In_EOF",
    "Decimation",
    "Dracolich_Boots",
    "Dracolich_Chaps",
    "Dracolich_Coif",
    "Dracolich_Hauberk",
    "Dracolich_Vambraces",
    "Dragon_Battleaxe",
    "Dragon_claw",
    "Dragon_claw_In_EOF",
    "Dragon_Scimitar",
    "Dragon_Scimitar_In_EOF",
    "Ek-ZekKil",
    "Eldritch_Crossbow",
    "Eldritch_Crossbow_In_EOF",
    "Elite_Sirenic_Chaps",
    "Elite_Sirenic_Hauberk",
    "Elite_Sirenic_Mask",
    "Elite_Tectonic_Mask",
    "Elite_Tectonic_Robe_Bottom",
    "Elite_Tectonic_Robe_Top",
    "Enhanced_Gloves_Of_Passage",
    "Essence_of_Finality",
    "Flanking",
    "Fractured_Staff_Of_Armadyl",
    "Guthix_Staff",
    "Guthix_Staff_In_EOF",
    "Iban's_staff",
    "Iban's_staff_In_EOF",
    "Jaws_of_the_Abyss",
    "Masterwork_Spear_of_Annihilation",
    "Noxious_Scythe",
    "Obliteration",
    "Occultist's_Ring",
    "Ode_To_Deceit",
    "Omni_Guard",
    "Pernixs_Quiver_Black",
    "Pernixs_Quiver_Blue",
    "Pernixs_Quiver_Green",
    "Pernixs_Quiver_Orange",
    "Pernixs_Quiver_Purple",
    "Pernixs_Quiver_Red",
    "Pernixs_Quiver_Yellow",
    "Reaver's_Ring",
    "Roar_Of_Awakening",
    "Royal_Crossbow",
    "Seren_godbow",
    "Seren_godbow_In_EOF",
    "Skull_Lantern",
    "Soulbound_Lantern",
    "Stalker's_Ring",
    "Vestments_Of_Havoc_Boots",
    "Vestments_Of_Havoc_Hood",
    "Vestments_Of_Havoc_Robe_Bottom",
    "Vestments_Of_Havoc_Robe_Top",
    "Zamorak_Bow",
    "Zamorak_Bow_In_EOF",
    "Zaros_Godsword",
    "Zorgoth's_Soul_Ring",

    # MISC
    "Adrenaline_potion",
    "Demon_Slayer",
    "Dive",
    "Dragon_Slayer",
    "Eat_Food",
    "Escape",
    "Limitless",
    "Move",
    "Onslaught",
    "Powerburst_of_vitality",
    "Quiver_ammo_slot_1",
    "Quiver_ammo_slot_2",
    "Reprisal",
    "Sacrifice",
    "Shatter",
    "Storm_Shards",
    "Target_Cycle",
    "Tuska's_Wrath",
    "Undead_Slayer",
    "Vulnerability_bomb",
    "Weapon_Special_Attack",

    # MELEE
    "Assault",
    "Backhand",
    "Balanced_Strike",
    "Barge",
    "Berserk",
    "Bladed_Dive",
    "Blood_Tendrils",
    "Chaos_Roar",
    "Cleave",
    "Decimate",
    "Destroy",
    "Dismember",
    "Flurry",
    "Forceful_Backhand",
    "Frenzy",
    "Fury",
    "Greater_Barge",
    "Greater_Flurry",
    "Greater_Fury",
    "Havoc",
    "Hurricane",
    "Kick",
    "Massacre",
    "Meteor_Strike",
    "Overpower",
    "Pulverise",
    "Punish",
    "Quake",
    "Sever",
    "Slaughter",
    "Slice",
    "Smash",
    "Stomp",

    # RANGE
    "Binding_Shot",
    "Bombardment",
    "Corruption_Shot",
    "Dazing_Shot",
    "Deadshot",
    "Death's_Swiftness",
    "Demoralise",
    "Fragmentation_Shot",
    "Greater_Dazing_Shot",
    "Greater_Death's_Swiftness",
    "Greater_Ricochet",
    "Incendiary_Shot",
    "Needle_Strike",
    "Piercing_Shot",
    "Rapid_Fire",
    "Ricochet",
    "Rout",
    "Salt_the_Wound",
    "Shadow_Tendrils",
    "Snap_Shot",
    "Snipe",
    "Tight_Bindings",
    "Unload",

    # MAGIC
    "Animate_Dead",
    "Asphyxiate",
    "Blood_Barrage",
    "Chain",
    "Combust",
    "Concentrated_Blast",
    "Corruption_Blast",
    "Deep_Impact",
    "Detonate",
    "Disruption_Shield",
    "Dragon_Breath",
    "Exsanguinate",
    "Greater_Chain",
    "Greater_Concentrated_Blast",
    "Greater_Sonic_Wave",
    "Greater_Sunshine",
    "Horror",
    "Impact",
    "Incite_Fear",
    "Intercept",
    "Magma_Tempest",
    "Metamorphosis",
    "Omnipower",
    "Shock",
    "Smoke_Cloud",
    "Smoke_Tendrils",
    "Sonic_Wave",
    "Spellbook_Swap",
    "Sunshine",
    "Surge",
    "Temporal_Anomaly",
    "Tsunami",
    "Vengeance",
    "Wild_Magic",
    "Wrack",
    "Wrack_and_Ruin",

    # NECROMANCY
    "Bloat",
    "Blood_Siphon",
    "Command_Phantom_Guardian",
    "Command_Putrid_Zombie",
    "Command_Skeleton_Warrior",
    "Command_Vengeful_Ghost",
    "Conjure_Phantom_Guardian",
    "Conjure_Putrid_Zombie",
    "Conjure_Skeleton_Warrior",
    "Conjure_Undead_Army",
    "Conjure_Vengeful_Ghost",
    "Death_Skulls",
    "Finger_of_Death",
    "Living_Death",
    "Necromancy",
    "Soul_Sap",
    "Soul_Strike",
    "Spectral_Scythe",
    "Spectral_Scythe_2",
    "Spectral_Scythe_3",
    "Touch_of_Death",
    "Volley_of_Souls",
    "Life_Transfer",
    "Threads_of_Fate",
    "Invoke_Lord_of_Bones",
    "Invoke_Death",
    "Darkness",
    "Split_Soul",
    "Death_Spark",

    # DEFENSE
    "Anticipation",
    "Barricade",
    "Bash",
    "Cease",
    "Debilitate",
    "Devotion",
    "Divert",
    "Freedom",
    "Ice_Asylum",
    "Immortality",
    "Ingenuity_of_the_Humans",
    "Natural_Instinct",
    "Preparation",
    "Provoke",
    "Reflect",
    "Rejuvenate",
    "Resonance",
    "Revenge",
]
def reorder_keybinds_json():
    if not os.path.exists(CONFIG_PATH):
        return  # silently skip if config not present

    with open(CONFIG_PATH, "r") as f:
        try:
            data = json.load(f)
        except json.JSONDecodeError:
            return  # invalid JSON, skip silently

    keybinds = data.get("ABILITY_KEYBINDS", {})
    ordered = OrderedDict()

    for key in DESIRED_ORDER:
        ordered[key] = keybinds.get(key, [])

    # Optionally preserve other unexpected keys
    for key in keybinds:
        if key not in ordered:
            ordered[key] = keybinds[key]

    # Save the new ordered JSON
    with open(CONFIG_PATH, "w") as f:
        json.dump({"ABILITY_KEYBINDS": ordered}, f, indent=2)

if __name__ == "__main__":
    reorder_keybinds_json()
