SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
PRESS_ZONE_X = 100  # Position where notes should be pressed... note its 10 pixels wide as well -> we need to move 10 pixels in .6 seconds?

TICK_DURATION = 0.6  # Each tick is 600ms
NOTE_SPEED = 100  # Pixels per tick?
ABILITY_DEFAULT_WIDTH = 75  # Default width of ability images
NOTE_SPACING_Y = 100  # Space between stacked notes


# Ability to Key Mapping (Supports Function Keys and Modifiers)
#Can use SHIFT, MOUSE, LCTRL, F1-F12
ABILITY_KEYBINDS = {

    #GEAR SWAPS
    "Royal_Crossbow": ["`"],
    "Noxious_Scythe": ["F4"],
    "Fractured_Staff_Of_Armadyl": ["F4"],
    "Soulbound_Lantern": ["F1"],
    "Omni_Guard": ["F2"],
    "Death_Guard": [],
    "Skull_Lantern": ["LCTRL", "F3"],
    "Roar_Of_Awakening": ["F1"],
    "Ode_To_Deceit": ["F2"],
    "Dark_Shard_Of_Leng": ["F1"],
    "Dark_Sliver_Of_Leng": ["F2"],

    #MISC
    "Move": ["MOUSE"],
    "Powerburst_of_vitality": [],
    "Demon_Slayer": [],
    "Dive": ["B"],
    "Dragon_Slayer": [],
    "Eat_Food": ["A"],
    "Escape": ["H"],
    "Essence_of_Finality": ["LCTRL", "2"],
    "Limitless": ["LCTRL", "1"],
    "Onslaught": [],
    "Quiver_ammo_slot_1": [],
    "Quiver_ammo_slot_2": [],
    "Reprisal": [],
    "Sacrifice": [],
    "Shatter": [],
    "Storm_Shards": [],
    "Tuska's_Wrath": [],
    "Undead_Slayer": [],
    "Weapon_Special_Attack": ["\\"],
    "Adrenaline_potion": ["G"],
    "Target_Cycle": ["Z"],
    "Vulnerability_bomb": ["V"],

    #MAGIC ABILITIES
    "Asphyxiate": ["E"],
    "Chain": ["5"],
    "Combust": [","],
    "Concentrated_Blast": [],
    "Corruption_Blast": ["4"],
    "Deep_Impact": ["SHIFT", "W"],
    "Detonate": ["T"],
    "Dragon_Breath": ["2"],
    "Greater_Chain": ["5"],
    "Greater_Concentrated_Blast": ["1"],
    "Greater_Sonic_Wave": ["3"],
    "Greater_Sunshine": ["Y"],
    "Horror": [""],
    "Impact": [],
    "Magma_Tempest": ["M"],
    "Metamorphosis": ["-"],
    "Omnipower": ["W"],
    "Shock": ["SHIFT", "O"],
    "Smoke_Tendrils": ["Q"],
    "Sonic_Wave": ["3"],
    "Sunshine": ["Y"],
    "Surge": ["["],
    "Tsunami": ["6"],
    "Wild_Magic": ["R"],
    "Wrack": ["3"],
    "Wrack_and_Ruin": ["3"],

    #MAGIC SPELLS
    "Exsanguinate": [],
    "Incite_Fear": [],
    "Temporal_Anomaly": [],
    "Disruption_Shield": [";"],
    "Vengeance": ["0"],
    "Smoke_Cloud": ["X"],
    "Blood_Barrage": ["F3"],
    "Intercept": ["K"],
    "Spellbook_Swap": ["P"],
    "Animate_Dead": ["F5"],

    #DEFENSE ABILITIES
    "Anticipation": ["SHIFT", "1"],
    "Barricade": [],
    "Bash": [],
    "Cease": ["O"],
    "Debilitate": ["LCTRL", "3"],
    "Devotion": ["SHIFT", "R"],
    "Divert": ["SHIFT", "3"],
    "[Freedom]": ["SHIFT", "2"],
    "Ice_Asylum": [],
    "Immortality": [],
    "Ingenuity_of_the_Humans": [],
    "Natural_Instinct": ["N"],
    "Preparation": [],
    "Provoke": [],
    "Reflect": ["SHIFT", "5"],
    "Rejuvenate": [],
    "Resonance": ["SHIFT", "4"],
    "Revenge": [],

    #MELEE ABILITIES
    "Assault": ["R"],
    "Backhand": ["Q"],
    "Balanced_Strike": [],
    "Barge": [],
    "Berserk": ["Y"],
    "Bladed_Dive": ["B"],
    "Blood_Tendrils": [","],
    "Chaos_Roar": ["I"],
    "Cleave": ["1"],
    "Decimate": ["1"],
    "Destroy": ["E"],
    "Dismember": ["6"],
    "Flurry": ["T"],
    "Forceful_Backhand": [],
    "Frenzy": [],
    "Fury": ["3"],
    "Greater_Barge": ["-"],
    "Greater_Flurry": ["T"],
    "Greater_Fury": ["3"],
    "Havoc": ["5"],
    "Hurricane": ["T"],
    "Kick": [],
    "Massacre": [],
    "Meteor_Strike": ["J"],
    "Overpower": ["U"],
    "Pulverise": [],
    "Punish": ["4"],
    "Quake": ["E"],
    "Sever": ["2"],
    "Slaughter": ["W"],
    "Slice": [],
    "Smash": [],
    "Stomp": [],

    #RANGED ABILITIES
    "Binding_Shot": ["4"],
    "Bombardment": ["T"],
    "Corruption_Shot": [","],
    "Dazing_Shot": [],
    "Deadshot": [],
    "Death's_Swiftness": [],
    "Demoralise": [],
    "Fragmentation_Shot": ["-"],
    "Greater_Dazing_Shot": ["2"],
    "Greater_Death's_Swiftness": ["Y"],
    "Greater_Ricochet": ["1"],
    "Incendiary_Shot": ["6"],
    "Needle_Strike": ["2"],
    "Piercing_Shot": ["3"],
    "Rapid_Fire": ["R"],
    "Ricochet": ["1"],
    "Rout": [],
    "Salt_the_Wound": ["W"],
    "Shadow_Tendrils": ["Q"],
    "Snap_Shot": ["E"],
    "Snipe": ["5"],
    "Tight_Bindings": ["4"],
    "Unload": [],

    #NECROMANCY ABILITIES
    "Bloat": ["Q"],
    "Blood_Siphon": [],
    "Command_Phantom_Guardian": [],
    "Command_Putrid_Zombie": [],
    "Command_Skeleton_Warrior": ["6"],
    "Command_Vengeful_Ghost": ["5"],
    "Conjure_Phantom_Guardian": [],
    "Conjure_Putrid_Zombie": [],
    "Conjure_Skeleton_Warrior": [],
    "Conjure_Undead_Army": ["4"],
    "Conjure_Vengeful_Ghost": [],
    "Death_Skulls": ["R"],
    "Finger_of_Death": ["-"],
    "Living_Death": ["Y"],
    "Necromancy": ["3"],
    "Soul_Sap": ["2"],
    "Soul_Strike": ["E"],
    "Spectral_Scythe": [],
    "Spectral_Scythe_2": [],
    "Spectral_Scythe_3": [],
    "Touch_of_Death": ["1"],
    "Volley_of_Souls": [","],
    "Life_Transfer": ["F3"],
    "Threads_of_Fate": ["T"],
    "Invoke_Lord_of_Bones": ["W"],
    "Invoke_Death": ["LCTRL", "F1"],
    "Darkness": ["F5"],
    "Split_Soul": ["F4"],
    "Death_Spark": [],

}

#Add weapons, release stored attack

# Abilities that should NOT trigger the dial animation
EXCLUDED_DIAL_ANIMATIONS = {"Surge", "Dive", "Bladed_Dive", "Escape", "Eat_Food",
                            "Powerburst_of_vitality", "Move", "Adrenaline_potion",
                            "Disruption_Shield", "Spellbook_Swap", "Exsanguinate",
                            "Incite_Fear", "Temporal_Anomaly", "Vengeance", "Target_Cycle",
                            "Smoke_Cloud", "Blood_Barrage","Vulnerability_bomb", "Royal_Crossbow",
                            "Noxious_Scythe", "Fractured_Staff_Of_Armadyl", "Soulbound_Lantern", "Omni_Guard",
                            "Death_Guard", "Skull_Lantern", "Roar_Of_Awakening", "Ode_To_Deceit",
                            "Dark_Shard_Of_Leng", "Dark_Sliver_Of_Leng",}


# Ability to Image Mapping
prefix="Temp_Images/30px-"
ABILITY_IMAGES = {
    "Anticipation": f"{prefix}Anticipation.png",
    "Asphyxiate": f"{prefix}Asphyxiate.png",
    "Assault": f"{prefix}Assault.png",
    "Backhand": f"{prefix}Backhand.png",
    "Balanced_Strike": f"{prefix}Balanced_Strike.png",
    "Barge": f"{prefix}Barge.png",
    "Barricade": f"{prefix}Barricade.png",
    "Bash": f"{prefix}Bash.png",
    "Berserk": f"{prefix}Berserk.png",
    "Binding_Shot": f"{prefix}Binding_Shot.png",
    "Bladed_Dive": f"{prefix}Bladed_Dive.png",
    "Bloat": f"{prefix}Bloat.png",
    "Blood_Siphon": f"{prefix}Blood_Siphon.png",
    "Blood_Tendrils": f"{prefix}Blood_Tendrils.png",
    "Bombardment": f"{prefix}Bombardment.png",
    "Cease": f"{prefix}Cease.png",
    "Chain": f"{prefix}Chain.png",
    "Chaos_Roar": f"{prefix}Chaos_Roar.png",
    "Cleave": f"{prefix}Cleave.png",
    "Combust": f"{prefix}Combust.png",
    "Command_Phantom_Guardian": f"{prefix}Command_Phantom_Guardian.png",
    "Command_Putrid_Zombie": f"{prefix}Command_Putrid_Zombie.png",
    "Command_Skeleton_Warrior": f"{prefix}Command_Skeleton_Warrior.png",
    "Command_Vengeful_Ghost": f"{prefix}Command_Vengeful_Ghost.png",
    "Concentrated_Blast": f"{prefix}Concentrated_Blast.png",
    "Conjure_Phantom_Guardian": f"{prefix}Conjure_Phantom_Guardian.png",
    "Conjure_Putrid_Zombie": f"{prefix}Conjure_Putrid_Zombie.png",
    "Conjure_Skeleton_Warrior": f"{prefix}Conjure_Skeleton_Warrior.png",
    "Conjure_Undead_Army": f"{prefix}Conjure_Undead_Army.png",
    "Conjure_Vengeful_Ghost": f"{prefix}Conjure_Vengeful_Ghost.png",
    "Corruption_Blast": f"{prefix}Corruption_Blast.png",
    "Corruption_Shot": f"{prefix}Corruption_Shot.png",
    "Dazing_Shot": f"{prefix}Dazing_Shot.png",
    "Deadshot": f"{prefix}Deadshot.png",
    "Death's_Swiftness": f"{prefix}Death's_Swiftness.png",
    "Death_Skulls": f"{prefix}Death_Skulls.png",
    "Debilitate": f"{prefix}Debilitate.png",
    "Decimate": f"{prefix}Decimate.png",
    "Deep_Impact": f"{prefix}Deep_Impact.png",
    "Demon_Slayer": f"{prefix}Demon_Slayer.png",
    "Demoralise": f"{prefix}Demoralise.png",
    "Destroy": f"{prefix}Destroy.png",
    "Detonate": f"{prefix}Detonate.png",
    "Devotion": f"{prefix}Devotion.png",
    "Dismember": f"{prefix}Dismember.png",
    "Dive": f"{prefix}Dive.png",
    "Divert": f"{prefix}Divert.png",
    "Dragon_Breath": f"{prefix}Dragon_Breath.png",
    "Dragon_Slayer": f"{prefix}Dragon_Slayer.png",
    "Eat_Food": f"{prefix}Eat_Food.png",
    "Escape": f"{prefix}Escape.png",
    "Essence_of_Finality": f"{prefix}Essence_of_Finality.png",
    "Finger_of_Death": f"{prefix}Finger_of_Death.png",
    "Flurry": f"{prefix}Flurry.png",
    "Forceful_Backhand": f"{prefix}Forceful_Backhand.png",
    "Fragmentation_Shot": f"{prefix}Fragmentation_Shot.png",
    "Freedom": f"{prefix}Freedom.png",
    "Frenzy": f"{prefix}Frenzy.png",
    "Fury": f"{prefix}Fury.png",
    "Greater_Barge": f"{prefix}Greater_Barge.png",
    "Greater_Chain": f"{prefix}Greater_Chain.png",
    "Greater_Concentrated_Blast": f"{prefix}Greater_Concentrated_Blast.png",
    "Greater_Dazing_Shot": f"{prefix}Greater_Dazing_Shot.png",
    "Greater_Death's_Swiftness": f"{prefix}Greater_Death's_Swiftness.png",
    "Greater_Flurry": f"{prefix}Greater_Flurry.png",
    "Greater_Fury": f"{prefix}Greater_Fury.png",
    "Greater_Ricochet": f"{prefix}Greater_Ricochet.png",
    "Greater_Sonic_Wave": f"{prefix}Greater_Sonic_Wave.png",
    "Greater_Sunshine": f"{prefix}Greater_Sunshine.png",
    "Havoc": f"{prefix}Havoc.png",
    "Horror": f"{prefix}Horror.png",
    "Hurricane": f"{prefix}Hurricane.png",
    "Ice_Asylum": f"{prefix}Ice_Asylum.png",
    "Immortality": f"{prefix}Immortality.png",
    "Impact": f"{prefix}Impact.png",
    "Incendiary_Shot": f"{prefix}Incendiary_Shot.png",
    "Ingenuity_of_the_Humans": f"{prefix}Ingenuity_of_the_Humans.png",
    "Kick": f"{prefix}Kick.png",
    "Limitless": f"{prefix}Limitless.png",
    "Living_Death": f"{prefix}Living_Death.png",
    "Magma_Tempest": f"{prefix}Magma_Tempest.png",
    "Massacre": f"{prefix}Massacre.png",
    "Metamorphosis": f"{prefix}Metamorphosis.png",
    "Meteor_Strike": f"{prefix}Meteor_Strike.png",
    "Natural_Instinct": f"{prefix}Natural_Instinct.png",
    "Necromancy": f"{prefix}Necromancy.png",
    "Needle_Strike": f"{prefix}Needle_Strike.png",
    "Omnipower": f"{prefix}Omnipower.png",
    "Onslaught": f"{prefix}Onslaught.png",
    "Overpower": f"{prefix}Overpower.png",
    "Piercing_Shot": f"{prefix}Piercing_Shot.png",
    "Preparation": f"{prefix}Preparation.png",
    "Provoke": f"{prefix}Provoke.png",
    "Pulverise": f"{prefix}Pulverise.png",
    "Punish": f"{prefix}Punish.png",
    "Quake": f"{prefix}Quake.png",
    "Quiver_ammo_slot_1": f"{prefix}Quiver_ammo_slot_1.png",
    "Quiver_ammo_slot_2": f"{prefix}Quiver_ammo_slot_2.png",
    "Rapid_Fire": f"{prefix}Rapid_Fire.png",
    "Reflect": f"{prefix}Reflect.png",
    "Rejuvenate": f"{prefix}Rejuvenate.png",
    "Reprisal": f"{prefix}Reprisal.png",
    "Resonance": f"{prefix}Resonance.png",
    "Revenge": f"{prefix}Revenge.png",
    "Ricochet": f"{prefix}Ricochet.png",
    "Rout": f"{prefix}Rout.png",
    "Sacrifice": f"{prefix}Sacrifice.png",
    "Salt_the_Wound": f"{prefix}Salt_the_Wound.png",
    "Sever": f"{prefix}Sever.png",
    "Shadow_Tendrils": f"{prefix}Shadow_Tendrils.png",
    "Shatter": f"{prefix}Shatter.png",
    "Shock": f"{prefix}Shock.png",
    "Slaughter": f"{prefix}Slaughter.png",
    "Slice": f"{prefix}Slice.png",
    "Smash": f"{prefix}Smash.png",
    "Smoke_Tendrils": f"{prefix}Smoke_Tendrils.png",
    "Snap_Shot": f"{prefix}Snap_Shot.png",
    "Snipe": f"{prefix}Snipe.png",
    "Sonic_Wave": f"{prefix}Sonic_Wave.png",
    "Soul_Sap": f"{prefix}Soul_Sap.png",
    "Soul_Strike": f"{prefix}Soul_Strike.png",
    "Surge": f"{prefix}Surge.png",
    "Wild_Magic": f"{prefix}Wild_Magic.png",
    "Wrack": f"{prefix}Wrack.png",
    "Wrack_and_Ruin": f"{prefix}Wrack_and_Ruin.png",
    "Life_Transfer": f"{prefix}Life_Transfer.png",
    "Threads_of_Fate": f"{prefix}Threads_of_Fate.png",
    "Invoke_Lord_of_Bones": f"{prefix}Invoke_Lord_of_Bones.png",
    "Invoke_Death": f"{prefix}Invoke_Death.png",
    "Darkness": f"{prefix}Darkness.png",
    "Split_Soul": f"{prefix}Split_Soul.png",
    "Adrenaline_potion": f"{prefix}Adrenaline_potion.png",
    "Weapon_Special_Attack": f"{prefix}Weapon_Special_Attack.png",
    "Touch_of_Death": f"{prefix}Touch_of_Death.png",
    "Tsunami": f"{prefix}Tsunami.png",
    "Tuska's_Wrath": f"{prefix}Tuska's_Wrath.png",
    "Undead_Slayer": f"{prefix}Undead_Slayer.png",
    "Unload": f"{prefix}Unload.png",
    "Volley_of_Souls": f"{prefix}Volley_of_Souls.png",
    "Target_Cycle": f"{prefix}Target_Cycle.png",
    "Vulnerability_bomb": f"{prefix}Vulnerability_bomb.png",
    "Smoke_Cloud": f"{prefix}Smoke_Cloud.png",
    "Blood_Barrage": f"{prefix}Blood_Barrage.png",
    "Intercept": f"{prefix}Intercept.png",
    "Spellbook_Swap": f"{prefix}Spellbook_Swap.png",
    "Animate_Dead": f"{prefix}Animate_Dead.png",
    "Exsanguinate": f"{prefix}Exsanguinate.png",
    "Incite_Fear": f"{prefix}Incite_Fear.png",
    "Temporal_Anomaly": f"{prefix}Temporal_Anomaly.png",
    "Disruption_Shield": f"{prefix}Disruption_Shield.png",
    "Vengeance": f"{prefix}Vengeance.png",
    "Move": f"{prefix}Move.png",
    "Powerburst_of_vitality": f"{prefix}Powerburst_of_vitality.png",
    "Noxious_Scythe": f"{prefix}Noxious_Scythe.png",
    "Royal_Crossbow": f"{prefix}Royal_Crossbow.png",
    "Soulbound_Lantern": f"{prefix}Soulbound_Lantern.png",
    "Omni_Guard": f"{prefix}Omni_Guard.png",
    "Death_Guard": f"{prefix}Death_Guard.png",
    "Skull_Lantern": f"{prefix}Skull_Lantern.png",
    "Roar_Of_Awakening": f"{prefix}Roar_Of_Awakening.png",
    "Ode_To_Deceit": f"{prefix}Ode_To_Deceit.png",
    "Dark_Shard_Of_Leng": f"{prefix}Dark_Shard_Of_Leng.png",
    "Dark_Sliver_Of_Leng": f"{prefix}Dark_Sliver_Of_Leng.png",
    "Sunshine": f"{prefix}Sunshine.png",
    "Fractured_Staff_Of_Armadyl": f"{prefix}Fractured_Staff_Of_Armadyl.png",
    "Storm_Shards": f"{prefix}Storm_Shards.png",
    "Stomp": f"{prefix}Stomp.png",
    "Tight_Bindings": f"{prefix}Tight_Bindings.png",
    "Spectral_Scythe": f"{prefix}Spectral_Scythe.png",
    "Spectral_Scythe_2": f"{prefix}Spectral_Scythe_2.png",
    "Spectral_Scythe_3": f"{prefix}Spectral_Scythe_3.png",
    "Death_Spark": f"{prefix}Death_Spark.png",


}


